name: Maven Build

# Trigger the workflow on push and pull request events to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner environment (using Ubuntu)

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK (Java Development Kit)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'   # You can change this to your required Java version
        distribution: 'adoptopenjdk'  # You can also choose a different distribution like OpenJDK

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository  # This caches the local Maven repository to speed up builds
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Run Maven clean install
    - name: Build with Maven
      run: mvn clean install

    # Optional: Step 5: Upload build artifacts (e.g., the JAR file) as an artifact for future use
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: maven-artifact
        path: target/*.jar
